name: Build and Release

on:
  push:
    paths:
      - "VERSION"

jobs:
  discover-subfolders:
    runs-on: ubuntu-latest
    outputs:
      subfolders: ${{ steps.set-output.outputs.subfolders }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Discover subfolders
        id: set-output
        run: |
          subfolders=$(ls -d */ | sed 's#/##')
          subfolders_json=$(echo "$subfolders" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "subfolders=$subfolders_json" >> $GITHUB_OUTPUT

  build:
    needs: discover-subfolders
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subfolder: ${{ fromJson(needs.discover-subfolders.outputs.subfolders) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Read version
        id: get_version
        run: |
          echo "VERSION=$(cat VERSION | head -n 1)" >> $GITHUB_ENV
          echo "VERSION_DESCRIPTION=$(cat VERSION | head -n 3 | tail -n 1)" >> $GITHUB_ENV
        working-directory: .

      - name: Build binary
        run: |
          cd ${{ matrix.subfolder }}
          go build -o ${{ matrix.subfolder }}

      - name: Archive binary
        run: |
          tar -czvf ${{ matrix.subfolder }}.tar.gz -C ${{ matrix.subfolder }} ${{ matrix.subfolder }}

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./${{ matrix.subfolder }}.tar.gz
          tag_name: ${{ env.VERSION }}
          body: ${{ env.VERSION_DESCRIPTION }}
          draft: false
          prerelease: false
